name: organize rules tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade organize-tool
          python3 -m pip install --upgrade unidecode
      - name: Python version
        run: python --version
      - name: Organize-tool version
        run: organize --version
      - name: Create test directories
        run: mkdir {~/Documents,~/Pictures,~/Music,~/Videos}
      - name: Create test files
        run: touch {~/Documents/test1.txt,~/Pictures/test2.txt,~/Music/test3.txt,~/Videos/test1.txt}
      - name: Run documents test
        run: organize sim documents-rule.yaml
      - name: Run duplicate files test
        run: organize sim duplicate-files-rule.yaml --working-dir=~/Documents
      - name: Run empty directories test
        run: organize sim empty-directories-rule.yaml --working-dir=~/Documents
      - name: Run empty files test
        run: organize sim empty-files-rule.yaml --working-dir=~/Documents
      - name: Run large files test
        run: organize sim large-files-rule.yaml --working-dir=~/Documents
